Repository hoffstadt/DearPyGui, pull requests merged in 2021-12, with the labels that each got.

#1478 fix: width/height ignored by file dialog #1476 and added min/max sizes
  DearPyGui/dearpygui/_dearpygui.pyi
  DearPyGui/dearpygui/_dearpygui_RTD.py
  DearPyGui/dearpygui/dearpygui.py
  DearPyGui/dearpygui/demo.py
  DearPyGui/src/core/AppItems/composite/mvFileDialog.cpp
  DearPyGui/src/core/AppItems/composite/mvFileDialog.h
  DearPyGui/vendor/ImGuiFileDialog/ImGuiFileDialog.cpp
  DearPyGui/vendor/ImGuiFileDialog/ImGuiFileDialog.h
Labels: state: ready, priority: high, type: bug

#1486 fix: handler deactivation #1485
  DearPyGui/src/core/AppItems/widget_handlers/mvItemHandlerRegistry.cpp
Labels: state: ready, priority: high, type: bug

#1508 fix (mvTableRow): table row not honoring "show" #1502
  DearPyGui/src/ui/AppItems/tables/mvTable.cpp
Labels: state: ready, priority: high, state: approved, type: bug

#1506 Autosize xy documentation
  DearPyGui/dearpygui/_dearpygui_RTD.py
  DearPyGui/dearpygui/_deprecated.py
  DearPyGui/src/ui/AppItems/mvAppItem.cpp
Labels: type: improvement, type: docs, state: changes requested

#1509 feat: exposed callback queue
  DearPyGui/dearpygui/_dearpygui.pyi
  DearPyGui/dearpygui/_dearpygui_RTD.py
  DearPyGui/dearpygui/_header.py
  DearPyGui/dearpygui/dearpygui.py
  DearPyGui/src/core/mvContext.h
  DearPyGui/src/modules/dearpygui.cpp
  DearPyGui/src/modules/dearpygui_commands.h
  DearPyGui/src/modules/dearpygui_parsers.h
  DearPyGui/src/ui/mvCallbackRegistry.cpp
  DearPyGui/src/ui/mvCallbackRegistry.h
  DearSandbox/sandbox.py
  setup.py
Labels: type: feature, state: ready, state: approved
